function ts_exportReport(fig)
%TS_EXPORTREPORT  G1 数据体检 Tab - "导出诊断 .md" 按钮回调 (顶层函数)
    if ~isappdata(fig, 'sanity_lastReport')
        uialert(fig, '请先选择一个 .mat 文件并完成分析', '未分析');
        return;
    end
    r       = getappdata(fig, 'sanity_lastReport');
    fs      = getappdata(fig, 'sanity_lastFs');
    fn      = getappdata(fig, 'sanity_currentFile');
    projRoot = getappdata(fig, 'sanity_projRoot');
    [~, name] = fileparts(fn);

    md = sprintf([ ...
        '# 数据体检报告: %s\n\n' ...
        '| 项 | 值 |\n|---|---|\n' ...
        '| 生成时间 | %s |\n' ...
        '| 数据文件 | `%s` |\n' ...
        '| 采样率 | %.3f MHz |\n' ...
        '| 工具 | `experiments/rx_sanity_check.m` |\n\n' ...
        '---\n\n' ...
        '## ① 数据完整性\n\n' ...
        '- 样本数: %d (%.3f s)\n' ...
        '- 唯一量化级数: %d (步长 %.6f)\n' ...
        '- 精确零样本: %d (%.4f%%)\n\n' ...
        '## ② 硬边界 / 削顶判定\n\n' ...
        '- 峰值幅度: %.4f %s\n' ...
        '- 边缘堆积比: %.2f  (未饱和 ≈0.3, 削顶 >1.2)\n' ...
        '- 触顶样本占比: %.3f%%\n' ...
        '- **是否 ADC 饱和**: %s\n\n' ...
        '## ③ 结论\n\n' ...
        '> %s\n\n' ...
        '---\n\n' ...
        '*由 sdr_showcase GUI 自动生成*\n'], ...
        name, char(datetime('now','Format','yyyy-MM-dd HH:mm:ss')), fn, fs/1e6, ...
        r.nSamples, r.nSamples/fs, ...
        r.nUniqueI, r.step, r.nExactZero, r.nExactZero/r.nSamples*100, ...
        r.envMax, ts_tern(r.atFullScale, '**[满量程]**', '[未满]'), ...
        r.edgeRatio, r.clipFrac*100, ts_tern(r.isClipped, '**是**', '否'), ...
        r.verdict);

    outFn = fullfile(projRoot, 'results', ...
                     sprintf('sanity_%s_%s.md', name, char(datetime('now','Format','yyyyMMdd_HHmmss'))));
    fid = fopen(outFn, 'w', 'n', 'UTF-8');
    if fid < 0
        uialert(fig, sprintf('无法写入:\n%s', outFn), '写入失败');
        return;
    end
    fwrite(fid, unicode2native(md, 'UTF-8'), 'uint8');
    fclose(fid);
    uialert(fig, sprintf('报告已保存:\n%s', outFn), '导出成功');
end